version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16
        environment:
          NODE_ENV: test
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "build project"
      - run: npm install
      - run: npm run build
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
